### ISSUE TITLE
Errore funzione findOperationById della classe PaymentGatewayClient

### ISSUE THREAD

**Issue by adicrescenzo79** [NexiPayments/sdk-php-npg#1]
Nella funzione findOperationById della classe PaymentGatewayClient è stata messa in POST mentre da documentazione API è in GET.

**Comment by NexiPayments** [comment]
Buongiorno,
vi ringraziamo per la segnalazione, abbiamo corretto le chiamate.

Per ulteriori informazioni o supporto nell'integrazione potete scriverci all'indirizzo tech.ecommerce@nexi.it

Restiamo a disposizione
