### ISSUE TITLE
Wrong HTTP method in documentation for /payment_methods

### ISSUE THREAD

**Issue by mlocati** [NexiPayments/sdk-php-npg#4]
In the documentation page https://developer.nexi.it/en/api/post-payment_methods we have the folowing:

![immagine](https://github.com/NexiPayments/sdk-php-npg/assets/928116/bff1850a-7af9-42e4-91e5-a757bcde8406)

That is, the `/payment_methods` should be invoked with a `POST` request.

But the SDK (correcly) uses the `GET` method, see
https://github.com/NexiPayments/sdk-php-npg/blob/98f879c61b552793349c0392d499a1e7da185c05/src/NexiSdk/PaymentGatewayClient.php#L309-L313

Is this the correct place to report documentation problems?

**Comment by NexiPayments** [comment]
Hi Michele,

Thank you for reporting, the portal will be corrected in an upcoming release.
