### ISSUE TITLE
Wrong code in Documentation / SDK / PHP

### ISSUE THREAD

**Issue by zeno-mioso** [NexiPayments/sdk-php-npg#5]
Just want to let you know that in the documentation the property "->setNotificationlUrl" in mispelled and I think probably needs to be corrected removing the "l" leading "Url" into this form "->setNotificationUrl"

<img width="1362" alt="Screenshot 2024-04-19 alle 13 04 22" src="https://github.com/NexiPayments/sdk-php-npg/assets/6981323/ddb0738b-7ad8-4471-8b26-095f0152af78">

**Comment by NexiPayments** [comment]
Hello,
thank you for the notification. We will correct the portal in an upcoming release.
